import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main>
        <nav className="navbar">
          <Link href='/' className="nav-link">
            Home
          </Link>
          <Link href="/part1" className="nav-link">
            Part 1
          </Link>
          <Link href="/part2" className="nav-link">
            Part 2
          </Link>
        </nav>
          {children}
        </main>
      </body>
    </html>
  )
}
